
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: "${GITHUB_CLIENT_ID}"
            client-secret: "${GITHUB_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: 8000
